BOOL __fastcall OnGamePacketReceived(LPBYTE aPacket,DWORD aLen);
extern void ChantTimerCheck();
extern bool Screenshot;
extern void ScreenshotCheck();
extern void EnchListedPlayers();
extern void EnchListedUnits();
extern	bool EnchBot;
extern DWORD WINAPI AutoPartyMemberThread(LPVOID P);
extern DWORD InGame;
VOID OnGameEvent(BOOL ExitGame);
char* CheckQuest(INT nQuest);
BOOL LoadIHPK();
BOOL UnloadIHPK();
BOOL Interact(DWORD dwUnitId, DWORD dwType, BOOL bCheckOverride);
BOOL CheckParty(int Status);
BOOL DeathMessage(char* opfer);
BOOL ChickenHostile(int nValue, DWORD PlayerID);
BOOL ChickenAim(int nValue, DWORD ID, DWORD AimID);
int RandomNumber(int high, int low);
void InviteAndLoot2(RosterUnit* pUnit, DWORD dwFlags);
void InviteAndLoot();
DWORD WINAPI DeathMessageThread(LPVOID P);
BOOL LoadBreakpoints(int nChar);
BOOL UnMax();